FROM rust:1.26.2-stretch as build

WORKDIR /usr/src/leita
COPY . .

RUN apt-get update && apt-get install -y musl musl-dev musl-tools
RUN cargo install
# Building for MUSL target since we are using alpine in runtime, which uses musl libc
RUN rustup target add x86_64-unknown-linux-musl
RUN cargo build --release --target=x86_64-unknown-linux-musl
RUN strip target/x86_64-unknown-linux-musl/release/leita

FROM alpine:3.7

COPY --from=build /usr/src/leita/target/x86_64-unknown-linux-musl/release/leita /usr/bin
COPY --from=build /usr/src/leita/hc_crawler/eventyr /hc_crawler/eventyr
RUN apk add --no-cache libgcc
# EXPOSE x
CMD ["leita"]
